openapi: 3.0.1
info:
  title: monster-clay-golem
  x-cortex-tag: monster-clay-golem
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: monstrosity
    challenge_rating: 13
    legendary: false
    armor_class: 13
    hit_points: 292
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-clay-golem
      alias: github-token-test
